### ISSUE TITLE
Project bootstrap

### ISSUE THREAD

**Issue by rodrigodealer** [brfutebol/hostdetect#1]
The idea behind this is to have a simple service that keeps tracking a list of hosts (from a yaml or something like that) and checks for open ports for these services. 

For instance: 

```
TCP 80
TCP 443
TCP 25
TCP/UDP 53
TCP/UDP 135
TCP/UDP 22
TCP/UDP 3389
TCP/UDP 21
```

And then we export this information to something like prometheus, where we can configure alarms.

**Comment by viniciushana** [comment]
This means we have 2 epics: the scanner and the API to let Prometheus scrape the metrics. Given that the scanner will generate the data that the API will expose, then I'm assuming they should start off as the same codebase - quicker to get something working. Therefore, one language only. WDYT?

**Comment by viniciushana** [comment]
Also, from my (limited) perception, getting it done in Go seems faster. Scala frameworks are usually followed with a bunch of boilerplate.

**Comment by rodrigodealer** [comment]
I was thinking about Go as well. Also to have this running in an infrastructure could be a pain in the ass having such a big docker image.

**Comment by viniciushana** [comment]
True. So, deployment could be through a Docker container that is provided a YAML (or any other format) of hosts to scan for. That would leave the code part pretty simple.

**Comment by kalinke** [comment]
Só quero causar mesmo <3

**Comment by rodrigodealer** [comment]
Só arrastar.
